### ISSUE TITLE
The significance of white space should be emphasized in the language guide. 

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#51]
The significance of white space should be emphasized. 

Line 86 in views/layouts/default.lavender the last bit of code is this:

This (space between parentheses and operator) does not work:

 li(class=className)
              a(
              href=urlPage[index],
              title=titles[index],
              target=target[index],
                ) =titles[index]

 This (no space between parentheses and operator) does work:

li(class=className)
              a(
              href=urlPage[index],
              title=titles[index],
              target=target[index],
                )=titles[index]

Feature or bug?

![variable text should be documented](https://cloud.githubusercontent.com/assets/11019935/6557882/e8f8661c-c64e-11e4-8b6c-1ae2ca442ad7.png)

![whitespace explanation](https://cloud.githubusercontent.com/assets/11019935/6558839/fb1e5c88-c654-11e4-9089-9cbf568d3963.png)

In the code example above, the white space did not add a new line, it just made the =titles[index] array reference fail to work.

**Comment by sugarPhlox** [comment]
Guide states 'Automagic whitespace management is hard and subject to change' as a head up into this. Whitespace is a finicky beast.
@sudo-reboot , thoughts on the '=titles[index]' issue?

**Comment by mowchan** [comment]
I always put my `=` flush with the selector I want the variable outputting in. I thought this was required whitespace.

**Comment by TomWoodward** [comment]
the `=` to make the content evaluated as an expression must be the last character of the node definition, just like the `-` to strip the trailing newline must be the last character of the node definition. spaces are not valid in node definitions outside of the attributes parentheses because the space marks the end of the node and the beginning of the content. so... no you can't have a space before the `=` and that is not a bug

i accidentally wrote a book, i'm just trying to tell you guys how it actually works. let me know if you need more clarity
