### ISSUE TITLE
The elseif documentation should be clarified.

### ISSUE THREAD

**Issue by avophile** [golavender/golavender.github.io#53]
The elseif documentation should be clarified. 

I was unable to get elseif to work. 

The documentation did not help me to understand why. 

![elseif documentation should be clarified](https://cloud.githubusercontent.com/assets/11019935/6558167/cc0090aa-c650-11e4-9d8d-48464dcea6a0.png)

**Comment by sugarPhlox** [comment]
@avophile  Lavender is built off of Jade and PHP, so the language is extremely similar. Feel free to find a more clear solution and add it here instead!

**Comment by mowchan** [comment]
Here's the jade documentation for conditionals: http://jade-lang.com/reference/conditionals/

**Comment by jennEDVT** [comment]
I'm finding some pretty funky behavior when I play around with conditionals as well. When I go to the Jade site and play around with their example on their codemirror, it all works perfectly just as I'd expect. However, when I copy the same code from jade and try playing around with it in lavender, I'm getting really inconsistent results. For example, if I paste the code in from jade and (do the obvious things like make sure everything is saved etc), then this is the result I get:

![image](https://cloud.githubusercontent.com/assets/4484493/6599505/8aab24da-c7e0-11e4-9a97-3c560830fd6e.png)

If, however, I delete the else if and the else, then I get what I'd expect:

![image](https://cloud.githubusercontent.com/assets/4484493/6599737/eae64eaa-c7e1-11e4-86bb-177243699ee4.png)

If, however, I re-paste in the else if and the else, I get the same thing (which is what I'd expect, except for the fact it didn't work the first time):

![image](https://cloud.githubusercontent.com/assets/4484493/6599539/d35d9514-c7e0-11e4-9469-42dee1a0d018.png)

Now, if I change it so that the first if is false, I get this, which is not what I'd expect:

![image](https://cloud.githubusercontent.com/assets/4484493/6599575/00a92f1a-c7e1-11e4-96da-dcf54e5cbdf3.png)

Likewise, I get strange results if I make the else if true:

![image](https://cloud.githubusercontent.com/assets/4484493/6599609/3409b532-c7e1-11e4-923e-5a809a1065d9.png)

However, if I delete everything and save it...

![image](https://cloud.githubusercontent.com/assets/4484493/6599636/50fed1ae-c7e1-11e4-86bc-4589abbb1d4c.png)

and then re-paste in the code, but delete the else statement, I get what I'd expect:

![image](https://cloud.githubusercontent.com/assets/4484493/6599669/7f0ee28c-c7e1-11e4-935e-6ca2ac35c6bd.png)

Can anyone replicate this issue? Or do these conditionals work as expected for everyone else? (again, when I played around with this code on the Jade website, it all worked perfectly, just like I'd expect it to.)

**Comment by sugarPhlox** [comment]
@jennEDVT Zach and I tested it in the office today, and the 'elseif' statement is space sensitive. If you run it as 'else if', Lavender only sees the 'else' and not the 'if'. It will throw an error 'Lavender_Exception:  else node used after something that has no boolean state' out of confusion.

So this solves the statement problem, we can clarify the guide now. Thank you for posting such a great explanation of your process!

**Comment by TomWoodward** [comment]
Lavender doesn't have the space in elseif, thats why weird stuff is
happening to you

**Comment by avophile** [comment]
There you have it!
