### ISSUE TITLE
Resize on Guide in browser = wonky navigation.

### ISSUE THREAD

**Issue by sugarPhlox** [golavender/golavender.github.io#69]
1. Scroll down on Guide page.
2. Re-size browser to mobile size (when loaded up originally in mobile, this problem does not appear)
3. Navigation bar will push itself behind the Guide page. 
4. When you scroll back to the top of the page, this navigation will disappear.

http://screencast.com/t/DGHcKH3cuO

**Comment by sugarPhlox** [comment]
@mowchan , you have any ideas on how to fix this?

**Comment by mowchan** [comment]
@sugarPhlox This is happening because the navigation is being affixed. You need to set styles to control the navigation when the `.affix` class is applied on mobile sizes.

**Comment by sugarPhlox** [comment]
@mowchan Even when this only occurs in browser on desktop? I was not able to replicate this with Android + Chrome, as well as iPhone + iOS 6&7 Safari.

**Comment by mowchan** [comment]
@sugarPhlox Yep. It's occurring only on desktop because affix isn't going to fire on a mobile viewport. It fires when the window is wide enough, then when you make it smaller it is still affixed. This should be addressed regardless of whether you can recreate it on those devices or not... people resize their browser all the time.

**Comment by mowchan** [comment]
I easily replicated it on iPad.

**Comment by sugarPhlox** [comment]
@mowchan true true. Alright, I'll pick this up. Thanks!
